Task 1: alert не выполнится, так как исключение перехыватывается неявным блоком try ... catch, и промис будет отклонен.